### This is the main way to configure the application (other than annotations).
### This file is in Yaml format but you can also configure spring boot using the traditional
### Java properties file format.

spring.jmx:
  enabled: false

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/dataprocessingApi?serverTimezone=Europe/Berlin
  username: root
  password:

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 9091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: spring-boot-rest-example
  version: 0.1
  description: boot-example default description

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

flyway:
  url: jdbc:mysql://localhost:3306/dataprocessingApi?serverTimezone=Europe/Berlin
  user: root
  password:
  baseline-on-migrate: true
---

logging:
  file: boot_exnample.log
  org.hibernate: INFO
  level:
    root: INFO
---